//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public Nullable<int> uid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string type { get; set; }
        public Nullable<double> price { get; set; }
        public string location { get; set; }
        public string image { get; set; }
        public Nullable<int> cid { get; set; }
    }
}
