//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public int id { get; set; }
        public Nullable<int> sid { get; set; }
        public Nullable<int> bid { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<double> price { get; set; }
    }
}
